[package]
name = "meida_house_admin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.39.3", features = ["rt", "macros"] }
structopt = "0.3.26"
serde_json = "1.0.127"
serde_with = { version = "3.8.0", features = ["time_0_3"] }
serde = { version = "1.0.144", features = ["derive"] }
derive_more = "0.99.17"
async-trait = "0.1.81"
diesel = { version = "2.2.3", features = ["mysql", "r2d2", "chrono", "numeric", "64-column-tables",] }
bigdecimal = { version = "0.4.5", features = ["serde"] }
chrono = { version = "0.4.23", features = ["serde"] }
dotenv = "0.15.0"
r2d2 = "0.8.10"
actix-web = { version = "4.9.0", features = ["openssl"] }
log = "0.4.22"
env_logger = "0.11.3"
uuid = { version = "1.10.0", features = ["v4"] }
qiniu-sdk = { version = "0.2.4", features = ["upload-token", "credential", "download"]}
qiniu-credential = "0.2.4"
qiniu-upload-token = "0.2.4"
url-escape = "0.1.1"
mysqlclient-sys = { version =  "0.4.1"  }
actix-cors = "0.7.0"
jsonwebtoken = "9"
time = "0.3.17"
argon2 = "0.5.0"
openssl = { version = "0.10", features = ["vendored"] }
actix-files = "0.6.6"

[[example]]
name = "jwt"
