
GET http://127.0.0.1:8000/api/v1/house/list HTTP/1.1
content-type: application/json

###

POST http://127.0.0.1:8000/api/v1/house/create HTTP/1.1
content-type: application/json

{
    "community_id": "b0298aac-94f1-4691-8e85-a2fa042b7118",
    "house_address": "string222",
    "house_type": "string",
    "area": 321,
    "bedrooms": 11,
    "living_rooms": 32,
    "bathrooms": 31,
    "orientation": "string",
    "decoration_status": "string",
    "status": "string",
    "house_description": "string",
    "house_image": "string",
    "owner_name": "string",
    "owner_phone": "string",
    "created_by": "string",
    "updated_by": "string"
}


###

POST http://127.0.0.1:8000/api/v1/house/update HTTP/1.1
content-type: application/json

{
    "house_id": "129cd56c-4f96-4aad-8273-c2bef2450ecd",
    "community_id": "b0298aac-94f1-4691-8e85-a2fa042b7118",
    "house_address": "荣陶胜",
    "house_type": "string",
    "area": 321,
    "bedrooms": 11,
    "living_rooms": 32,
    "bathrooms": 31,
    "orientation": "string",
    "decoration_status": "string",
    "status": "string",
    "house_description": "string",
    "house_image": "string",
    "owner_name": "string",
    "owner_phone": "string",
    "created_by": "string",
    "updated_by": "string"
}