
POST http://127.0.0.1:8000/api/v1/rental_house/save HTTP/1.1
content-type: application/json

{
  "house_id": "4917738f-f750-4a78-a36d-fb7ba6bd97ba",
  "rent_pice": 12.3,
  "rent_low_pice": 125
}

###

GET http://127.0.0.1:8000/api/v1/rental_house/list_listed HTTP/1.1
content-type: application/json


